# create your drupal and postgres config here, based off the last assignment
version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/

services:
  drupalPgsql3:
    #new custom
    image: custom-drupal  #uniquie name , different than last container
    build: . #new
#      context: .
#      dockerfile: nginx.Dockerfile
    ports:
      - '80:80'  #new was 80:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
        # this takes advantage of the feature in Docker that a new anonymous
        # volume (which is what we're creating here) will be initialized with the
        # existing content of the image at the same location
      - drupal-sites:/var/www/html/sites
    restart: always
  postgresSql2:  #use this word instead of localhost|postgres in advanced settings
    image: postgres
    environment:
      POSTGRES_PASSWORD: example2    #or D="example2"
    volumes:   #new
      - drupal-data:/var/lib/postgresql/data
    restart: always
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data:    #new
